language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

sudo: required

before_script:
  - composer self-update
  - composer install
  - chmod 777 -R database/
  - touch database/database.sqlite
  - sed -i '1s/^/DB_CONNECTION=sqlite\n/' .env

script:
 - vendor/bin/phpunit
