language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer install
  - touch database/database.sqlite
  - sed -i '1s/^/DB_CONNECTION=sqlite /' .env

script:
 - vendor/bin/phpunit
