language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - nightly

services:
  - mysql

before_script:
  - composer self-update
  - composer install
  - mysql -e 'create database api_bbb;'
  
scripts: 
  - vendor/bin/phpunit
